### ISSUE TITLE
npm run dev: Error: Cannot find module '../lib/cli'

### ISSUE THREAD

**Issue by DigiConvent** [seanpmaxwell/express-generator-typescript#86] opened 2023-10-20 09:35 UTC
When generating a new project (without having a name specified) and then running that project using `npm run dev`, I get a 

```js
> express-gen-ts@0.0.0 dev
> nodemon

node:internal/modules/cjs/loader:958
  throw err;
  ^

Error: Cannot find module '../lib/cli'
Require stack:
- /<path>/<projectname>/node_modules/.bin/nodemon
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/<path>/<projectname>/node_modules/.bin/nodemon:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/<path>/<projectname>/node_modules/.bin/nodemon'
  ]
}

Node.js v18.9.0
```

Running `npm install` didn't help. Steps to reproduce: 

`npx express-generator-typescript`, run with `npm run dev`.

**Comment by seanpmaxwell** [comment] 2023-10-20 22:28
hmm, i just ran the command and I'm not able to reproduce, that error looks weird, like nodemon didn't get downloaded

**Comment by seanpmaxwell** [comment] 2023-10-20 22:29
maybe try to clear the npx cache

**Comment by seanpmaxwell** [comment] 2024-03-01 18:16
closing this cause haven't gotten a response for a while

**Closed by seanpmaxwell** 2024-03-01 18:16 UTC
