### ISSUE TITLE
How to run unit test in CI

### ISSUE THREAD

**Issue by kenakamu** [seanpmaxwell/express-generator-typescript#22] opened 2020-03-10 16:39 UTC
What's the best way to CI and run unit test as part of it?
It seems only "watch" option is available

**Comment by seanpmaxwell** [comment] 2020-03-10 17:14
I you want to bypass the commands in package.json you could just run the unit tests directly with `ts-node ./spec`. If you want to change jasmine's settings they're in `./spec/index.ts`

**Comment by kenakamu** [comment] 2020-03-10 17:31
Thanks. Any guidance or recommendation how?
It seems jasmine keep running even though I directly calling it. I need to change index.ts to call             jasmine.exitCodeCompletion(passed); in onComplete.

I also want to add JUnit report. Any idea?

**Comment by seanpmaxwell** [comment] 2020-03-10 18:02
Sorry can't give any advise on JUnit reports. I'm not sure why Jasmine is not exiting for you. When I run this command directly: `ts-node -r tsconfig-paths/register ./spec` everything runs and stops just fine.

**Comment by kenakamu** [comment] 2020-03-11 02:35
Stop means it comes back to the state that you can enter next command? In my case, it runs okay and seems it waits for something..

**Comment by seanpmaxwell** [comment] 2020-03-12 17:27
Have you tried running that command from the root of the app?

**Comment by kenakamu** [comment] 2020-03-12 18:15
Yes, that's what I am doing. I updated the code to workaround it and if it doesn't repro in your environment, please ignore it. Could be my environment issue.

**Comment by seanpmaxwell** [comment] 2020-03-12 18:52
Okay, well Ima close this issue for now. But let me know if anything comes that you think might be helpful. I can't reproduce the error so not much help I can do.

**Closed by seanpmaxwell** 2020-03-12 18:52 UTC
